### PR TITLE
title, fonts and paragraph base style updae

### PR DESCRIPTION
**Pull request by kappowas**
Title base style update,
paragraph base style update,
added some comments in css 
added fonts and changed it in reset.css

### CODE REVIEW

**Review by kamidem — COMMENTED** [review]
siaip kas yra, atrodo gerai - tu greitas! bet dar lygtais title stiliaus truksta

**Comment by kappowas** [comment]
> siaip kas yra, atrodo gerai - tu greitas! bet dar lygtais title stiliaus truksta

.bg-title-center arba bg-title-left yra title stilius

**Review by AisteKara — DISMISSED** [review]
Tinka patinka

**Review by kamidem — APPROVED** [review]
good stuff!

**Review by AisteKara — APPROVED** [review]
Good to see some work done

**Pull request merged**
